POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVjNjk0MjY1NTU2YjRmMTE1YzczZGFhMyIsImlhdCI6MTU1MDQ3Njk3OH0.ee8tzArY2uZjdvzKgfE0r03IyK05mn9R9Mq8kaPk7MI

{
    "title": "Web token authorization for dummies",
    "author": "Jane Doe",
    "url": "www.testblog.com",
    "likes": 200
}